#ifndef CLASP_HPP
#define CLASP_HPP
#include "command.hpp"
#include "flag.hpp"
#include "value.hpp"
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define CLASP_VERSION_MAJOR 0
#define CLASP_VERSION_MINOR 1
#define CLASP_VERSION_PATCH 0
#define CLASP_VERSION_STRING TOSTRING(CLASP_VERSION_MAJOR) "." TOSTRING(CLASP_VERSION_MINOR) "." TOSTRING(CLASP_VERSION_PATCH)
#endif //CLASP_HPP
